project_id = "srsokoncsaiogszeielc"

[functions.create-order]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.get-users]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false
